//! AWS collector menu. 136 collectors across 12 categories.
//! Order, category names, and item groupings match the pre-refactor
//! global menu byte-for-byte (cross-checked against the ground-truth
//! boundaries that used to live in the now-deleted global category
//! index, not the stale inline index comments that used to live in
//! collector_data.rs).

use super::ProviderCategory;

pub const AWS_CATEGORIES: &[ProviderCategory] = &[
    ProviderCategory {
        name: "App & Network Services",
        items: &[
            ("api-gateway", "API Gateway              "),
            ("cloudfront", "CloudFront Distributions "),
            ("lambda-config", "Lambda Configuration     "),
            ("lambda-permissions", "Lambda Permissions       "),
            ("route53-zones", "Route53 Hosted Zones     "),
            ("route53-resolver", "Route53 Resolver Rules   "),
        ],
    },
    ProviderCategory {
        name: "Audit Trail",
        items: &[
            ("config-recorder", "AWS Config Recorder      "),
            ("config-rules", "AWS Config Rules         "),
            ("cfn-drift", "CloudFormation Drift     "),
            ("cloudtrail", "CloudTrail API"),
            ("ct-changes", "CloudTrail Change Events"),
            ("cloudtrail-config", "CloudTrail Configuration "),
            ("ct-selectors", "CloudTrail Evt Selectors "),
            ("ct-full-config", "CloudTrail Full Config   "),
            ("ct-validation", "CloudTrail Log Validation"),
            (
                "s3",
                "CloudTrail S3            (7 months, requires s3-bucket, JSON)",
            ),
            ("ct-s3-policy", "CloudTrail S3 Policy     "),
            (
                "config-compliance",
                "Config Compliance History(all rules, CSV)",
            ),
            ("config-history", "Config Resource History  "),
            ("config-timeline", "Config Resource Timeline"),
            ("config-snapshot", "Config Snapshot (PiT)"),
            ("ct-config-changes", "CT Config Change Events  "),
            ("ct-iam-changes", "CT IAM Changes (Hi-Risk) "),
            ("ct-logs-insights", "CT Logs Insights Query   "),
        ],
    },
    ProviderCategory {
        name: "Compute",
        items: &[
            ("asg", "Auto Scaling Groups      "),
            ("ec2-detailed", "EC2 Details (AMI/IMDS)   "),
            ("ec2-config", "EC2 Instance Config      "),
            ("ec2-instances", "EC2 Instances            "),
            ("launch-templates", "EC2 Launch Templates     "),
            ("ssm-allowlist", "SSM Application Allowlist"),
            ("ssm-assoc-status", "SSM Instance Associations Status"),
            ("ssm-automation", "SSM Automation Runbooks "),
            ("ssm-maint-windows", "SSM Maintenance Windows  "),
            ("ssm-instances", "SSM Managed Instances    "),
            ("ssm-params", "SSM Parameter Store      "),
            ("ssm-baselines", "SSM Patch Baselines      "),
            ("ssm-patches", "SSM Patch Compliance     "),
            (
                "ssm-patch-detail",
                "SSM Patch Detail         (per instance, CSV)",
            ),
            (
                "ssm-patch-exec",
                "SSM Patch Executions     (command history, CSV)",
            ),
            ("ssm-patch-summary", "SSM Patch Summary"),
            ("time-sync", "Time Sync Config (SSM)   "),
        ],
    },
    ProviderCategory {
        name: "Containers",
        items: &[
            ("ecr-config", "ECR Repo Config          "),
            ("ecs", "ECS Clusters             "),
            ("eks", "EKS Clusters             "),
        ],
    },
    ProviderCategory {
        name: "Database & Backup",
        items: &[
            ("backup", "AWS Backup API"),
            ("backup-plans", "AWS Backup Plans         "),
            ("backup-vaults", "Backup Vault Config      "),
            ("backup-region-settings", "Backup Region Settings   "),
            ("doc-repo-backup", "Doc Repo Backup Config  "),
            ("rds-backup-config", "RDS Backup Config        "),
            ("rds-inventory", "RDS Inventory            "),
            ("rds", "RDS Snapshots"),
            ("rds-snapshots", "RDS Snapshots            "),
        ],
    },
    ProviderCategory {
        name: "Encryption & Secrets",
        items: &[
            ("ebs-encryption", "EBS Default Encryption   "),
            ("ebs-config", "EBS Encryption Config    "),
            ("kms-config", "KMS Key Config (Full)    "),
            ("kms-policies", "KMS Key Policies         "),
            ("kms", "KMS Keys                 "),
            ("secrets", "Secrets Manager          "),
            ("secrets-policies", "Secrets Manager Policies "),
        ],
    },
    ProviderCategory {
        name: "Identity & Access",
        items: &[
            ("access-analyzer", "IAM Access Analyzer      "),
            ("iam-access-keys", "IAM Access Keys          "),
            ("iam-account-summary", "IAM Account Summary      "),
            ("iam-certs", "IAM Certificates         "),
            ("iam-cred-report", "IAM Credential Report   "),
            ("iam-password-policy", "IAM Password Policy      "),
            ("iam-policies", "IAM Policies             "),
            ("iam-role-policies", "IAM Role Policies        "),
            ("iam-trusts", "IAM Role Trust Policies  "),
            ("iam-roles", "IAM Roles                "),
            ("iam-user-policies", "IAM User Policies        "),
            ("iam-users", "IAM Users                "),
            ("saml-providers", "SAML IdP Config          "),
        ],
    },
    ProviderCategory {
        name: "Monitoring & Events",
        items: &[
            ("cw-alarms", "CloudWatch Alarms        "),
            ("cw-log-groups", "CloudWatch Log Groups    "),
            ("cw-config-alarms", "CW Alarms (All)          "),
            ("cw-log-config", "CW Log Group Config      "),
            (
                "change-event-rules",
                "EventBridge Change Rules (event-pattern, CSV)",
            ),
            ("eventbridge-rules", "EventBridge Rules        "),
            ("metric-filters", "Log Metric Filters/Alarms"),
            ("metric-filter-config", "Metric Filter Config    "),
            ("sns-policies", "SNS Topic Policies       "),
            ("sns", "SNS Topic Subscribers    "),
        ],
    },
    ProviderCategory {
        name: "Network",
        items: &[
            ("acm", "ACM Certificates         "),
            ("alb-logs", "ALB Access Log Config    "),
            ("igw", "Internet Gateways        "),
            ("elb-full-config", "Load Balancer Full Config"),
            ("elb-listeners", "Load Balancer Listeners  "),
            ("elb", "Load Balancers           "),
            ("nat-gateways", "NAT Gateways             "),
            ("nacl", "Network ACLs             "),
            ("nfw-failclosed", "NetworkFirewall Fail-Closed"),
            ("public-resources", "Publicly Exposed Res.    "),
            ("rt-config", "Route Table Config       "),
            ("route-tables", "Route Tables             "),
            ("sg-config", "Security Group Config    "),
            ("security-groups", "Security Groups          "),
            ("session-timeouts", "Session Timeouts        "),
            ("tgw-peering", "TransitGateway + VPC Peer"),
            ("vpc-config", "VPC Configuration        "),
            ("vpc-endpoints", "VPC Endpoints            "),
            ("vpc-flow-logs", "VPC Flow Logging         "),
            ("vpc", "VPCs                     "),
            ("waf-config", "WAF Full Config          "),
            ("waf-logging", "WAF Logging Config       "),
            ("waf", "WAF Regional Web ACLs    "),
        ],
    },
    ProviderCategory {
        name: "Organization & Account",
        items: &[
            ("account-contacts", "Account Alt. Contacts    "),
            (
                "org-config",
                "AWS Org Config           (requires org master, CSV)",
            ),
            ("scp", "Org SCPs                 (requires org admin, CSV)"),
            ("resource-tags", "Resource Tags            "),
        ],
    },
    ProviderCategory {
        name: "Security Detection",
        items: &[
            ("ami-default-creds", "AMI Default Cred Scan   "),
            ("guardduty-config", "GuardDuty Config         "),
            ("guardduty", "GuardDuty Findings       "),
            ("gd-full-config", "GuardDuty Full Config    "),
            ("guardduty-malware", "GuardDuty Malware Scans "),
            ("guardduty-runtime", "GuardDuty Runtime Coverage"),
            ("guardduty-rules", "GuardDuty Suppression    "),
            ("inspector-history", "Inspector Findings Hist. "),
            ("inspector-config", "Inspector2 Config        "),
            ("inspector-ecr-images", "Inspector2 ECR Images    "),
            ("inspector", "Inspector2 Findings      "),
            ("macie", "Macie Findings           "),
            ("securityhub", "Security Hub Findings    "),
            ("sh-config", "SecurityHub Config       "),
            ("sh-standards", "SecurityHub Standards    "),
            ("inspector-sbom", "Inspector2 SBOM Export   "),
        ],
    },
    ProviderCategory {
        name: "Storage",
        items: &[
            ("dynamodb", "DynamoDB Tables          "),
            ("ebs", "EBS Volumes              "),
            ("efs", "EFS File Systems         "),
            ("elasticache", "ElastiCache Clusters     "),
            ("elasticache-global", "ElastiCache Global DS    "),
            ("s3-logging", "S3 Bucket Access Logging "),
            ("s3-policies", "S3 Bucket Policies       "),
            ("s3-bucket-policy", "S3 Bucket Policy (Full)  "),
            ("s3-config", "S3 Buckets Config        "),
            ("s3-data-events", "S3 Data Events Config    "),
            ("s3-encryption", "S3 Encryption Config     "),
            ("s3-logging-config", "S3 Logging Config        "),
            ("s3-public-access", "S3 Public Access Block   "),
        ],
    },
];
