// ---------------------------------------------------------------------------
// Static collector menu data (matches COLLECTOR_CATEGORIES index boundaries)
// ---------------------------------------------------------------------------

pub const COLLECTOR_ITEMS: &[(&str, &str)] = &[
    // ── App Layer & DNS ── (0..6)
    ("api-gateway", "API Gateway              "),
    ("cloudfront", "CloudFront Distributions "),
    ("lambda-config", "Lambda Configuration     "),
    ("lambda-permissions", "Lambda Permissions       "),
    ("route53-zones", "Route53 Hosted Zones     "),
    ("route53-resolver", "Route53 Resolver Rules   "),
    // ── Audit Trail ── (6..23)
    ("config-recorder", "AWS Config Recorder      "),
    ("config-rules", "AWS Config Rules         "),
    ("cfn-drift", "CloudFormation Drift     "),
    ("cloudtrail", "CloudTrail API"),
    ("ct-changes", "CloudTrail Change Events"),
    ("cloudtrail-config", "CloudTrail Configuration "),
    ("ct-selectors", "CloudTrail Evt Selectors "),
    ("ct-full-config", "CloudTrail Full Config   "),
    ("ct-validation", "CloudTrail Log Validation"),
    (
        "s3",
        "CloudTrail S3            (7 months, requires s3-bucket, JSON)",
    ),
    ("ct-s3-policy", "CloudTrail S3 Policy     "),
    (
        "config-compliance",
        "Config Compliance History(all rules, CSV)",
    ),
    ("config-history", "Config Resource History  "),
    ("config-timeline", "Config Resource Timeline"),
    ("config-snapshot", "Config Snapshot (PiT)"),
    ("ct-config-changes", "CT Config Change Events  "),
    ("ct-iam-changes", "CT IAM Changes (Hi-Risk) "),
    // ── Compute ── (23..37)
    ("asg", "Auto Scaling Groups      "),
    ("ec2-detailed", "EC2 Details (AMI/IMDS)   "),
    ("ec2-config", "EC2 Instance Config      "),
    ("ec2-instances", "EC2 Instances            "),
    ("launch-templates", "EC2 Launch Templates     "),
    ("ssm-maint-windows", "SSM Maintenance Windows  "),
    ("ssm-instances", "SSM Managed Instances    "),
    ("ssm-params", "SSM Parameter Store      "),
    ("ssm-baselines", "SSM Patch Baselines      "),
    ("ssm-patches", "SSM Patch Compliance     "),
    (
        "ssm-patch-detail",
        "SSM Patch Detail         (per instance, CSV)",
    ),
    (
        "ssm-patch-exec",
        "SSM Patch Executions     (command history, CSV)",
    ),
    ("ssm-patch-summary", "SSM Patch Summary"),
    ("time-sync", "Time Sync Config (SSM)   "),
    // ── Containers ── (37..41)
    ("ecr-scan", "ECR Image Scan Findings  "),
    ("ecr-config", "ECR Repo Config          "),
    ("ecs", "ECS Clusters             "),
    ("eks", "EKS Clusters             "),
    // ── Database & Backup ── (41..48)
    ("backup", "AWS Backup API"),
    ("backup-plans", "AWS Backup Plans         "),
    ("backup-vaults", "Backup Vault Config      "),
    ("rds-backup-config", "RDS Backup Config        "),
    ("rds-inventory", "RDS Inventory            "),
    ("rds", "RDS Snapshots"),
    ("rds-snapshots", "RDS Snapshots            "),
    // ── Encryption & Secrets ── (48..55)
    ("ebs-encryption", "EBS Default Encryption   "),
    ("ebs-config", "EBS Encryption Config    "),
    ("kms-config", "KMS Key Config (Full)    "),
    ("kms-policies", "KMS Key Policies         "),
    ("kms", "KMS Keys                 "),
    ("secrets", "Secrets Manager          "),
    ("secrets-policies", "Secrets Manager Policies "),
    // ── Identity & Access ── (55..67)
    ("access-analyzer", "IAM Access Analyzer      "),
    ("iam-access-keys", "IAM Access Keys          "),
    ("iam-account-summary", "IAM Account Summary      "),
    ("iam-certs", "IAM Certificates         "),
    ("iam-password-policy", "IAM Password Policy      "),
    ("iam-policies", "IAM Policies             "),
    ("iam-role-policies", "IAM Role Policies        "),
    ("iam-trusts", "IAM Role Trust Policies  "),
    ("iam-roles", "IAM Roles                "),
    ("iam-user-policies", "IAM User Policies        "),
    ("iam-users", "IAM Users                "),
    ("saml-providers", "SAML IdP Config          "),
    // ── Monitoring & Events ── (67..77)
    ("cw-alarms", "CloudWatch Alarms        "),
    ("cw-log-groups", "CloudWatch Log Groups    "),
    ("cw-config-alarms", "CW Alarms (All)          "),
    ("cw-log-config", "CW Log Group Config      "),
    (
        "change-event-rules",
        "EventBridge Change Rules (event-pattern, CSV)",
    ),
    ("eventbridge-rules", "EventBridge Rules        "),
    ("metric-filters", "Log Metric Filters/Alarms"),
    ("metric-filter-config", "Metric Filter Config    "),
    ("sns-policies", "SNS Topic Policies       "),
    ("sns", "SNS Topic Subscribers    "),
    // ── Network ── (77..97)
    ("acm", "ACM Certificates         "),
    ("alb-logs", "ALB Access Log Config    "),
    ("igw", "Internet Gateways        "),
    ("elb-full-config", "Load Balancer Full Config"),
    ("elb-listeners", "Load Balancer Listeners  "),
    ("elb", "Load Balancers           "),
    ("nat-gateways", "NAT Gateways             "),
    ("nacl", "Network ACLs             "),
    ("public-resources", "Publicly Exposed Res.    "),
    ("rt-config", "Route Table Config       "),
    ("route-tables", "Route Tables             "),
    ("sg-config", "Security Group Config    "),
    ("security-groups", "Security Groups          "),
    ("vpc-config", "VPC Configuration        "),
    ("vpc-endpoints", "VPC Endpoints            "),
    ("vpc-flow-logs", "VPC Flow Logging         "),
    ("vpc", "VPCs                     "),
    ("waf-config", "WAF Full Config          "),
    ("waf-logging", "WAF Logging Config       "),
    ("waf", "WAF Regional Web ACLs    "),
    // ── Organization & Account ── (97..101)
    ("account-contacts", "Account Alt. Contacts    "),
    (
        "org-config",
        "AWS Org Config           (requires org master, CSV)",
    ),
    ("scp", "Org SCPs                 (requires org admin, CSV)"),
    ("resource-tags", "Resource Tags            "),
    // ── Security Detection ── (101..113)
    ("guardduty-config", "GuardDuty Config         "),
    ("guardduty", "GuardDuty Findings       "),
    ("gd-full-config", "GuardDuty Full Config    "),
    ("guardduty-rules", "GuardDuty Suppression    "),
    ("inspector-history", "Inspector Findings Hist. "),
    ("inspector-config", "Inspector2 Config        "),
    ("inspector-ecr-images", "Inspector2 ECR Images    "),
    ("inspector", "Inspector2 Findings      "),
    ("macie", "Macie Findings           "),
    ("securityhub", "Security Hub Findings    "),
    ("sh-config", "SecurityHub Config       "),
    ("sh-standards", "SecurityHub Standards    "),
    // ── Storage ── (113..126)
    ("dynamodb", "DynamoDB Tables          "),
    ("ebs", "EBS Volumes              "),
    ("efs", "EFS File Systems         "),
    ("elasticache", "ElastiCache Clusters     "),
    ("elasticache-global", "ElastiCache Global DS    "),
    ("s3-logging", "S3 Bucket Access Logging "),
    ("s3-policies", "S3 Bucket Policies       "),
    ("s3-bucket-policy", "S3 Bucket Policy (Full)  "),
    ("s3-config", "S3 Buckets Config        "),
    ("s3-data-events", "S3 Data Events Config    "),
    ("s3-encryption", "S3 Encryption Config     "),
    ("s3-logging-config", "S3 Logging Config        "),
    ("s3-public-access", "S3 Public Access Block   "),
];

// ---------------------------------------------------------------------------
// Available AWS regions
// ---------------------------------------------------------------------------

pub const AWS_REGIONS: &[&str] = &[
    // North America
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
    "ca-central-1",
    // Europe
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    // Asia Pacific
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    // South America
    "sa-east-1",
];
